python3 -m training_script --data steel --model unet_v1 --lr 1e-3 --device cuda:0
python3 -m training_script --data steel --model unet_paper --lr 1e-3 --device cuda:0
python3 -m training_script --data aitex --model unet_v1 --lr 1e-3 --device cuda:0
python3 -m training_script --data aitex --model unet_paper --lr 1e-3 --device cuda:0
python3 -m training_script --data steel --model simplefcn --lr 1e-3 --device cuda:0
python3 -m training_script --data aitex --model simplefcn --lr 1e-3 --device cuda:0
python3 -m training_script --data steel --model unet_v1 --lr 0.5e-4 --device cuda:0
python3 -m training_script --data steel --model unet_paper --lr 0.5e-4 --device cuda:0
python3 -m training_script --data aitex --model unet_v1 --lr 0.5e-4 --device cuda:0
python3 -m training_script --data aitex --model unet_paper --lr 0.5e-4 --device cuda:0
python3 -m training_script --data steel --model simplefcn --lr 0.5e-4 --device cuda:0
python3 -m training_script --data aitex --model simplefcn --lr 0.5e-4 --device cuda:0